name: Docker build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          Docker_User: ${{ secrets.D_U  }}
          Docker_Pass: ${{ secrets.D_P }}
        run: |
          docker login -u $Docker_User -p Docker_Pass
         
      - name: docker build python 
        run: |
         docker image build . -t localhost:5000/app-calc
      - name: push docker image to private repo in docker hub
        run: |
          docker push python-calc-image/localhost:5000/app-calc

   
