name: Docker build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3   
      - name: docker build python and tag the image to the docker hub repo
        run: |
         docker image build . -t python-calc-image
         docker tag python-calc-image dockkcodewqrkd/python-calc-image
      - name: docker logout
        run: |
          docker logout
      - name: docker login
        env:
          Docker_User: ${{ secrets.D_U  }}
          Docker_Pass: ${{ secrets.D_P }}
        run: |
          sudo docker login -u $Docker_User -p $Docker_Pass
      - name: push docker image to private repo in docker hub
        run: |
          sudo docker push dockkcodewqrkd/python-calc-image

   
